/// SPI flash operations over one all-PIO flash bus.
///
/// PL022 is intentionally not used. All phases, including classic 1-1-1 SPI,
/// run through PIO so the same engine can switch between 1-1-1, 1-1-2,
/// 1-2-2, 1-1-4 and 1-4-4. Bulk reads use two DMA channels: one drains the
/// PIO RX FIFO and one feeds one token per byte into the TX FIFO so the state
/// machine clocks exactly the requested number of bytes and then stalls.
use embassy_futures::join::join;
use embassy_rp::Peri;
use embassy_rp::clocks::clk_sys_freq;
use embassy_rp::dma::Channel as DmaChannel;
use embassy_rp::gpio::{Flex, Level, Pull};
use embassy_rp::peripherals::PIO0;
use embassy_rp::pio::{
    Common, Config, Direction, FifoJoin, LoadedProgram, Pin, Pio, PioPin, ShiftConfig,
    ShiftDirection, StateMachine,
};
use embassy_time::{Duration, Instant};
use fixed::traits::ToFixed;
use fixed::types::U24F8;
use fixed::types::extra::U8;

use crate::config;
use crate::protocol::IoMode;

type Pio0Common<'d> = Common<'d, PIO0>;
type Pio0Sm0<'d> = StateMachine<'d, PIO0, 0>;
type Pio0Pin<'d> = Pin<'d, PIO0>;
type Pio0Program<'d> = LoadedProgram<'d, PIO0>;

const PIO_CYCLES_PER_SCK: u32 = 5;
const PIO_WAIT_TIMEOUT_ITERS: u32 = 10_000;

struct FlashPioPrograms<'d> {
    duplex1: Pio0Program<'d>,
    tx1: Pio0Program<'d>,
    tx2: Pio0Program<'d>,
    tx4: Pio0Program<'d>,
    rx1: Pio0Program<'d>,
    rx2: Pio0Program<'d>,
    rx4: Pio0Program<'d>,
}

pub struct SpiFlash<'d> {
    _common: Pio0Common<'d>,
    sm: Pio0Sm0<'d>,
    dma_rx: DmaChannel<'d>,
    dma_tx: DmaChannel<'d>,
    programs: FlashPioPrograms<'d>,
    io0: Pio0Pin<'d>,
    io1: Pio0Pin<'d>,
    io2: Pio0Pin<'d>,
    io3: Pio0Pin<'d>,
    sck: Pio0Pin<'d>,
    cs: Flex<'d>,
    clock_divider: U24F8,
    effective_freq_hz: u32,
    active_rx_width: u8,
    rx_bit_correction: bool,
    rx_correction_prev: u8,
    force_busy_until: Option<Instant>,
}

impl<'d> SpiFlash<'d> {
    #[allow(clippy::too_many_arguments)]
    pub fn new(
        mut pio: Pio<'d, PIO0>,
        dma_rx: DmaChannel<'d>,
        dma_tx: DmaChannel<'d>,
        io0: Peri<'d, impl PioPin + 'd>,
        io1: Peri<'d, impl PioPin + 'd>,
        io2: Peri<'d, impl PioPin + 'd>,
        io3: Peri<'d, impl PioPin + 'd>,
        sck: Peri<'d, impl PioPin + 'd>,
        cs: Flex<'d>,
    ) -> Self {
        let mut io0 = pio.common.make_pio_pin(io0);
        let mut io1 = pio.common.make_pio_pin(io1);
        let mut io2 = pio.common.make_pio_pin(io2);
        let mut io3 = pio.common.make_pio_pin(io3);
        let mut sck = pio.common.make_pio_pin(sck);

        io0.set_pull(Pull::None);
        io1.set_pull(Pull::None);
        io2.set_pull(Pull::Up);
        io3.set_pull(Pull::Up);
        sck.set_pull(Pull::None);

        // The flash bus is synchronous to the SCK generated by this PIO state
        // machine. Bypass the GPIO input synchronizers so center-sampled reads
        // do not pick up an extra multi-sysclk delay at higher SCK rates.
        io0.set_input_sync_bypass(true);
        io1.set_input_sync_bypass(true);
        io2.set_input_sync_bypass(true);
        io3.set_input_sync_bypass(true);

        let programs = FlashPioPrograms {
            duplex1: pio.common.load_program(&assemble_duplex_program(1)),
            tx1: pio.common.load_program(&assemble_tx_program(1)),
            tx2: pio.common.load_program(&assemble_tx_program(2)),
            tx4: pio.common.load_program(&assemble_tx_program(4)),
            rx1: pio.common.load_program(&assemble_rx_program(1)),
            rx2: pio.common.load_program(&assemble_rx_program(2)),
            rx4: pio.common.load_program(&assemble_rx_program(4)),
        };

        let mut this = Self {
            _common: pio.common,
            sm: pio.sm0,
            dma_rx,
            dma_tx,
            programs,
            io0,
            io1,
            io2,
            io3,
            sck,
            cs,
            clock_divider: U24F8::from_num(PIO_CYCLES_PER_SCK),
            effective_freq_hz: config::DEFAULT_SPI_FREQ_HZ,
            active_rx_width: 1,
            rx_bit_correction: false,
            rx_correction_prev: 0,
            force_busy_until: None,
        };

        this.set_frequency(config::DEFAULT_SPI_FREQ_HZ);
        this.idle_io();
        this
    }

    // =========================================================================
    // Runtime PIO clock configuration
    // =========================================================================

    /// Change the generated SCK frequency. The tuned PIO bit cells use five PIO
    /// cycles per full SCK period, giving enough phase resolution for reliable
    /// 24 MHz reads from an SPI flash emulator.
    pub fn set_frequency(&mut self, freq_hz: u32) {
        let target = freq_hz
            .clamp(1, config::MAX_SPI_FREQ_HZ)
            .min(clk_sys_freq() / PIO_CYCLES_PER_SCK);
        // Match embassy-rp's PIO SPI divider calculation: use a U64 fixed-point
        // intermediate so clk_sys_freq() (typically 125 MHz) does not overflow
        // U24F8's ~16 MHz integer range before the final small divider is known.
        let clock_freq = clk_sys_freq().to_fixed::<fixed::FixedU64<U8>>();
        let pio_bit_freq = target
            .saturating_mul(PIO_CYCLES_PER_SCK)
            .to_fixed::<fixed::FixedU64<U8>>();
        self.clock_divider = (clock_freq / pio_bit_freq).to_fixed();
        self.effective_freq_hz = target;
    }

    fn needs_1bit_rx_correction(&self) -> bool {
        false
    }

    fn correct_next_rx_byte(&mut self, raw: u8) -> u8 {
        let corrected = (self.rx_correction_prev << 1) | (raw >> 7);
        self.rx_correction_prev = raw;
        corrected
    }

    // =========================================================================
    // CS and idle pin control
    // =========================================================================

    #[inline]
    pub fn cs_assert(&mut self) {
        self.sm.set_enable(false);
        self.sm.clear_fifos();
        self.sm.set_pins(Level::Low, &[&self.sck, &self.io0]);
        self.sm
            .set_pin_dirs(Direction::Out, &[&self.sck, &self.io0]);
        self.sm.set_pin_dirs(Direction::In, &[&self.io1]);
        self.wp_hold_high();
        self.cs.set_low();
        self.cs.set_as_output();
    }

    #[inline]
    pub fn cs_deassert(&mut self) {
        self.sm.set_enable(false);
        self.cs.set_high();
        self.idle_io();
    }

    fn idle_io(&mut self) {
        self.sm.set_enable(false);
        self.sm.clear_fifos();
        self.sm
            .set_pin_dirs(Direction::In, &[&self.sck, &self.io0, &self.io1]);
        self.wp_hold_high();
        self.io0.set_pull(Pull::None);
        self.io1.set_pull(Pull::None);
        self.io2.set_pull(Pull::None);
        self.io3.set_pull(Pull::None);
        self.sck.set_pull(Pull::None);
        self.cs.set_pull(Pull::None);
        self.cs.set_as_input();
    }

    fn wp_hold_high(&mut self) {
        self.sm.set_pins(Level::High, &[&self.io2, &self.io3]);
        self.sm
            .set_pin_dirs(Direction::Out, &[&self.io2, &self.io3]);
    }

    fn configure_tx(&mut self, width: u8) {
        self.sm.set_enable(false);
        self.sm.clear_fifos();

        let mut cfg = Config::default();
        cfg.clock_divider = self.clock_divider;
        cfg.fifo_join = FifoJoin::Duplex;
        cfg.shift_out = ShiftConfig {
            auto_fill: false,
            threshold: 32,
            direction: ShiftDirection::Left,
        };

        let program = match width {
            1 => &self.programs.tx1,
            2 => &self.programs.tx2,
            _ => &self.programs.tx4,
        };
        cfg.use_program(program, &[&self.sck]);
        match width {
            1 => cfg.set_out_pins(&[&self.io0]),
            2 => cfg.set_out_pins(&[&self.io0, &self.io1]),
            _ => cfg.set_out_pins(&[&self.io0, &self.io1, &self.io2, &self.io3]),
        }

        self.sm.set_config(&cfg);
        self.sm.set_pin_dirs(Direction::Out, &[&self.sck]);
        self.sm.set_pins(Level::Low, &[&self.sck]);

        match width {
            1 => {
                self.sm.set_pin_dirs(Direction::Out, &[&self.io0]);
                self.sm.set_pin_dirs(Direction::In, &[&self.io1]);
                self.wp_hold_high();
            }
            2 => {
                self.sm
                    .set_pin_dirs(Direction::Out, &[&self.io0, &self.io1]);
                self.wp_hold_high();
            }
            _ => self.sm.set_pin_dirs(
                Direction::Out,
                &[&self.io0, &self.io1, &self.io2, &self.io3],
            ),
        }

        self.sm.restart();
        self.sm.clkdiv_restart();
        self.clear_tx_stall();
        self.sm.set_enable(true);
        self.wait_tx_stalled();
    }

    fn configure_rx(&mut self, width: u8) {
        self.sm.set_enable(false);
        self.sm.clear_fifos();
        self.rx_bit_correction = false;

        let mut cfg = Config::default();
        cfg.clock_divider = self.clock_divider;
        cfg.fifo_join = FifoJoin::Duplex;
        cfg.shift_in = ShiftConfig {
            auto_fill: true,
            threshold: 8,
            direction: ShiftDirection::Left,
        };
        cfg.shift_out = ShiftConfig {
            auto_fill: true,
            threshold: 8,
            direction: ShiftDirection::Left,
        };

        let program = match width {
            1 => &self.programs.rx1,
            2 => &self.programs.rx2,
            _ => &self.programs.rx4,
        };
        cfg.use_program(program, &[&self.sck]);
        match width {
            1 => cfg.set_in_pins(&[&self.io1]),
            2 => cfg.set_in_pins(&[&self.io0, &self.io1]),
            _ => cfg.set_in_pins(&[&self.io0, &self.io1, &self.io2, &self.io3]),
        }

        self.sm.set_config(&cfg);
        self.sm.set_pin_dirs(Direction::Out, &[&self.sck]);
        self.sm.set_pins(Level::Low, &[&self.sck]);

        match width {
            1 => {
                self.sm.set_pins(Level::Low, &[&self.io0]);
                self.sm.set_pin_dirs(Direction::Out, &[&self.io0]);
                self.sm.set_pin_dirs(Direction::In, &[&self.io1]);
                self.wp_hold_high();
            }
            2 => {
                self.sm.set_pin_dirs(Direction::In, &[&self.io0, &self.io1]);
                self.wp_hold_high();
            }
            _ => self
                .sm
                .set_pin_dirs(Direction::In, &[&self.io0, &self.io1, &self.io2, &self.io3]),
        }

        self.active_rx_width = width;
        self.sm.restart();
        self.sm.clkdiv_restart();
        self.clear_tx_stall();
        self.sm.set_enable(true);
    }

    fn configure_duplex1(&mut self) {
        self.sm.set_enable(false);
        self.sm.clear_fifos();
        self.rx_bit_correction = false;

        let mut cfg = Config::default();
        cfg.clock_divider = self.clock_divider;
        cfg.fifo_join = FifoJoin::Duplex;
        cfg.shift_in = ShiftConfig {
            auto_fill: true,
            threshold: 8,
            direction: ShiftDirection::Left,
        };
        cfg.shift_out = ShiftConfig {
            auto_fill: true,
            threshold: 8,
            direction: ShiftDirection::Left,
        };

        cfg.use_program(&self.programs.duplex1, &[&self.sck]);
        cfg.set_out_pins(&[&self.io0]);
        cfg.set_in_pins(&[&self.io1]);

        self.sm.set_config(&cfg);
        self.sm.set_pins(Level::Low, &[&self.sck, &self.io0]);
        self.sm
            .set_pin_dirs(Direction::Out, &[&self.sck, &self.io0]);
        self.sm.set_pin_dirs(Direction::In, &[&self.io1]);
        self.wp_hold_high();

        self.active_rx_width = 1;
        self.sm.restart();
        self.sm.clkdiv_restart();
        self.sm.set_enable(true);
    }

    fn clear_tx_stall(&mut self) {
        let _ = self.sm.tx().stalled();
    }

    fn wait_tx_stalled(&mut self) -> bool {
        for _ in 0..PIO_WAIT_TIMEOUT_ITERS {
            if self.sm.tx().stalled() {
                return true;
            }
            cortex_m::asm::nop();
        }

        false
    }

    fn wait_rx_ready(&mut self) -> bool {
        for _ in 0..PIO_WAIT_TIMEOUT_ITERS {
            if !self.sm.rx().empty() {
                return true;
            }
            cortex_m::asm::nop();
        }

        false
    }

    fn push_tx_bounded(&mut self, value: u32) -> bool {
        for _ in 0..PIO_WAIT_TIMEOUT_ITERS {
            if self.sm.tx().try_push(value) {
                return true;
            }
            cortex_m::asm::nop();
        }

        false
    }

    fn write_byte_configured(&mut self, value: u8) {
        self.clear_tx_stall();
        if self.push_tx_bounded((value as u32) << 24) {
            let _ = self.wait_tx_stalled();
        }
    }

    fn write_byte_width(&mut self, value: u8, width: u8) {
        self.configure_tx(width);
        self.write_byte_configured(value);
    }

    fn read_byte_configured(&mut self) -> u8 {
        if self.push_tx_bounded(0) && self.wait_rx_ready() {
            self.sm.rx().pull() as u8
        } else {
            0xff
        }
    }

    fn duplex1_write_read_byte_configured(&mut self, value: u8) -> Option<u8> {
        self.clear_tx_stall();
        if self.push_tx_bounded((value as u32) << 24) && self.wait_rx_ready() {
            Some(self.sm.rx().pull() as u8)
        } else {
            None
        }
    }

    fn write_1bit_bytes_duplex(&mut self, data: &[u8]) -> bool {
        self.configure_duplex1();
        self.write_1bit_bytes_duplex_configured(data)
    }

    fn write_1bit_bytes_duplex_configured(&mut self, data: &[u8]) -> bool {
        for &byte in data {
            if self.duplex1_write_read_byte_configured(byte).is_none() {
                return false;
            }
        }
        true
    }

    fn write_address_1bit_duplex_configured(&mut self, address: u32, addr_len: u8) -> bool {
        if addr_len == 4
            && self
                .duplex1_write_read_byte_configured((address >> 24) as u8)
                .is_none()
        {
            return false;
        }

        self.duplex1_write_read_byte_configured((address >> 16) as u8)
            .is_some()
            && self
                .duplex1_write_read_byte_configured((address >> 8) as u8)
                .is_some()
            && self
                .duplex1_write_read_byte_configured(address as u8)
                .is_some()
    }

    fn dummy_clocks(&mut self, width: u8, cycles: u8) {
        if cycles == 0 {
            return;
        }

        self.configure_tx(width);
        self.dummy_clocks_configured(width, cycles);
    }

    fn dummy_clocks_configured(&mut self, width: u8, cycles: u8) {
        let cycles_per_byte = 8 / width;
        let bytes = cycles.div_ceil(cycles_per_byte);
        for _ in 0..bytes {
            self.write_byte_configured(0);
        }
    }

    fn write_address_configured(&mut self, address: u32, addr_len: u8) {
        if addr_len == 4 {
            self.write_byte_configured((address >> 24) as u8);
        }
        self.write_byte_configured((address >> 16) as u8);
        self.write_byte_configured((address >> 8) as u8);
        self.write_byte_configured(address as u8);
    }

    // =========================================================================
    // Blocking operations (called from USB handler context via critical_section)
    // =========================================================================

    /// Perform a standard 1-1-1 transceive: write command bytes, then read
    /// response bytes while CS remains asserted.
    pub fn transceive_blocking(&mut self, write_data: &[u8], read_buf: &mut [u8]) {
        if matches!(write_data.first(), Some(&config::SPI_CMD_READ_STATUS))
            && self
                .force_busy_until
                .is_some_and(|until| Instant::now() < until)
        {
            read_buf.fill(config::SPI_STATUS_WIP);
            return;
        }

        self.cs_assert();
        self.configure_duplex1();
        for &byte in write_data {
            if self.duplex1_write_read_byte_configured(byte).is_none() {
                read_buf.fill(0xff);
                self.cs_deassert();
                return;
            }
        }
        if self.needs_1bit_rx_correction() && !read_buf.is_empty() {
            let Some(prev) = self.duplex1_write_read_byte_configured(0) else {
                read_buf.fill(0xff);
                self.cs_deassert();
                return;
            };
            self.rx_correction_prev = prev;
            for byte in read_buf.iter_mut() {
                if let Some(raw) = self.duplex1_write_read_byte_configured(0) {
                    *byte = self.correct_next_rx_byte(raw);
                } else {
                    *byte = 0xff;
                }
            }
        } else {
            for byte in read_buf.iter_mut() {
                *byte = self.duplex1_write_read_byte_configured(0).unwrap_or(0xff);
            }
        }
        self.cs_deassert();
    }

    /// Write-only standard 1-1-1 transaction.
    pub fn write_only_blocking(&mut self, write_data: &[u8]) {
        self.cs_assert();
        let _ = self.write_1bit_bytes_duplex(write_data);
        self.cs_deassert();

        if let Some(duration) = erase_busy_duration(write_data) {
            self.force_busy_until = Some(Instant::now() + duration);
        }
    }

    // =========================================================================
    // Async operations (called from bulk worker task)
    // =========================================================================

    /// Begin a read sequence. Opcode is 1-bit unless QPI is requested.
    /// Address/mode/data phases follow the current Dediprog I/O mode.
    pub async fn start_read(
        &mut self,
        opcode: u8,
        address: u32,
        addr_len: u8,
        io_mode: IoMode,
        mode_byte: Option<u8>,
        dummy_cycles: u8,
    ) {
        self.wait_for_forced_busy_window().await;

        self.cs_assert();

        let opcode_width = if io_mode == IoMode::Qpi { 4 } else { 1 };
        let address_width = io_mode.address_width();
        let read_width = io_mode.read_width();

        if opcode_width == 1 {
            self.configure_duplex1();
            let _ = self.duplex1_write_read_byte_configured(opcode);
        } else {
            self.write_byte_width(opcode, opcode_width);
        }

        if address_width == 1 {
            // Keep 1-bit command/address phases on the full-duplex engine. The
            // TX-only engine can otherwise lose the final bit when immediately
            // reconfigured for a multi-lane address/read phase; EM100 traces saw
            // 0xbb degraded to 0xba in that case.
            self.configure_duplex1();
            let _ = self.write_address_1bit_duplex_configured(address, addr_len);
            if let Some(mode) = mode_byte {
                let _ = self.duplex1_write_read_byte_configured(mode);
            }
            if dummy_cycles > 0 && read_width == 1 {
                let cycles_per_byte = 8 / read_width;
                let bytes = dummy_cycles.div_ceil(cycles_per_byte);
                for _ in 0..bytes {
                    let _ = self.duplex1_write_read_byte_configured(0);
                }
            } else {
                self.dummy_clocks(read_width, dummy_cycles);
            }
        } else {
            // For DIO/QIO, keep address, mode and same-width dummy clocks in one
            // TX configuration so the final bit of a phase cannot be truncated by
            // state-machine reconfiguration.
            self.configure_tx(address_width);
            self.write_address_configured(address, addr_len);
            if let Some(mode) = mode_byte {
                self.write_byte_configured(mode);
            }
            if dummy_cycles > 0 && read_width == address_width {
                self.dummy_clocks_configured(address_width, dummy_cycles);
            } else {
                self.dummy_clocks(read_width, dummy_cycles);
            }
        }

        self.configure_rx(read_width);
        if read_width == 1 && self.needs_1bit_rx_correction() {
            self.rx_correction_prev = self.read_byte_configured();
            self.rx_bit_correction = true;
        }
    }

    /// DMA-read one block of data. CS must already be asserted via `start_read()`.
    pub async fn read_block(&mut self, buf: &mut [u8], io_mode: IoMode) {
        let width = io_mode.read_width();
        if self.active_rx_width != width {
            self.configure_rx(width);
        }

        let len = buf.len();
        let (rx, tx) = self.sm.rx_tx();
        let mut dma_rx = self.dma_rx.reborrow();
        let mut dma_tx = self.dma_tx.reborrow();
        let rx_transfer = rx.dma_pull(&mut dma_rx, buf, false);
        let tx_transfer = tx.dma_push_zeros::<u32>(&mut dma_tx, len);
        join(rx_transfer, tx_transfer).await;

        if self.rx_bit_correction {
            for byte in buf.iter_mut() {
                *byte = self.correct_next_rx_byte(*byte);
            }
        }
    }

    /// Finish a multi-block transfer (deassert CS).
    pub fn end_transfer(&mut self) {
        self.cs_deassert();
    }

    /// Write one page to flash using standard 1-1-1 page program.
    pub async fn write_page(&mut self, opcode: u8, address: u32, addr_len: u8, data: &[u8]) {
        self.wait_for_forced_busy_window().await;

        // ---- Write Enable ----
        self.cs_assert();
        let _ = self.write_1bit_bytes_duplex(&[config::SPI_CMD_WRITE_ENABLE]);
        self.cs_deassert();
        embassy_time::Timer::after_micros(1).await;

        // ---- Page Program ----
        self.cs_assert();
        self.configure_duplex1();
        let _ = self.duplex1_write_read_byte_configured(opcode);
        let _ = self.write_address_1bit_duplex_configured(address, addr_len);
        let _ = self.write_1bit_bytes_duplex_configured(data);
        self.cs_deassert();

        // ---- Wait for completion ----
        // Some emulators do not assert WIP quickly enough for an immediate status
        // read after CS deassertion. Give the page-program operation a short head
        // start before polling so the following page's WREN/program sequence is
        // not ignored while the target is still internally busy.
        embassy_time::Timer::after_micros(1_000).await;
        self.poll_wip().await;
    }

    /// Poll the flash status register until the WIP (Write In Progress) bit clears.
    async fn poll_wip(&mut self) {
        loop {
            self.cs_assert();
            self.configure_duplex1();
            let _ = self.duplex1_write_read_byte_configured(config::SPI_CMD_READ_STATUS);
            let status = self.duplex1_write_read_byte_configured(0).unwrap_or(0xff);
            self.cs_deassert();

            if status & config::SPI_STATUS_WIP == 0 {
                break;
            }

            embassy_time::Timer::after_micros(50).await;
        }
    }

    async fn wait_for_forced_busy_window(&mut self) {
        loop {
            match self.force_busy_until {
                Some(until) if Instant::now() < until => {
                    embassy_time::Timer::after_millis(1).await;
                }
                Some(_) => {
                    self.force_busy_until = None;
                    embassy_time::Timer::after_millis(25).await;
                    break;
                }
                None => break,
            }
        }
    }
}

fn assemble_duplex_program(width: u8) -> pio::Program<32> {
    let side_set = pio::SideSet::new(false, 1, false);
    let mut a = pio::Assembler::<32>::new_with_side_set(side_set);
    let mut wrap_target = a.label();
    let mut wrap_source = a.label();

    a.bind(&mut wrap_target);
    // Five-cycle mode-0 bit cell tuned for 24 MHz. OUT drives MOSI during the
    // two-cycle low phase; two high-side NOPs delay MISO sampling until late in
    // the high phase, which avoids the 24 MHz bit-shift seen with earlier cells.
    a.out_with_delay_and_side_set(pio::OutDestination::PINS, width, 1, 0);
    a.nop_with_side_set(1);
    a.nop_with_side_set(1);
    a.r#in_with_side_set(pio::InSource::PINS, width, 1);
    a.bind(&mut wrap_source);

    a.assemble_with_wrap(wrap_source, wrap_target)
}

fn assemble_tx_program(width: u8) -> pio::Program<32> {
    let groups_per_byte = 8 / width;
    let side_set = pio::SideSet::new(false, 1, false);
    let mut a = pio::Assembler::<32>::new_with_side_set(side_set);
    let mut wrap_target = a.label();
    let mut wrap_source = a.label();
    let mut bitloop = a.label();

    a.bind(&mut wrap_target);
    a.pull_with_side_set(false, true, 0);
    a.set_with_side_set(pio::SetDestination::X, groups_per_byte - 1, 0);
    a.bind(&mut bitloop);
    a.out_with_delay_and_side_set(pio::OutDestination::PINS, width, 1, 0);
    a.jmp_with_delay_and_side_set(pio::JmpCondition::XDecNonZero, &mut bitloop, 2, 1);
    a.bind(&mut wrap_source);

    a.assemble_with_wrap(wrap_source, wrap_target)
}

fn assemble_rx_program(width: u8) -> pio::Program<32> {
    let side_set = pio::SideSet::new(false, 1, false);
    let mut a = pio::Assembler::<32>::new_with_side_set(side_set);
    let mut wrap_target = a.label();
    let mut wrap_source = a.label();

    a.bind(&mut wrap_target);
    // Read-only five-cycle bit cell matching the full-duplex sample phase. OUT
    // NULL consumes one lane-group from OSR so autopull supplies one byte worth
    // of clocks per TX FIFO word, while IN samples late in the SCK high phase.
    a.out_with_delay_and_side_set(pio::OutDestination::NULL, width, 1, 0);
    a.nop_with_side_set(1);
    a.nop_with_side_set(1);
    a.r#in_with_side_set(pio::InSource::PINS, width, 1);
    a.bind(&mut wrap_source);

    a.assemble_with_wrap(wrap_source, wrap_target)
}

fn erase_busy_duration(write_data: &[u8]) -> Option<Duration> {
    let opcode = *write_data.first()?;
    match opcode {
        // 4 KiB sector erase. EM100 usually finishes much sooner, but this keeps
        // the host from issuing the next command before WIP is visible.
        0x20 | 0x21 => Some(Duration::from_millis(250)),
        // 32 KiB block erase.
        0x52 | 0x5c => Some(Duration::from_millis(750)),
        // 64 KiB block erase.
        0xd8 | 0xdc => Some(Duration::from_millis(1_500)),
        // Whole-chip erase. EM100 takes long enough that immediately following
        // page-program commands can be ignored unless we hold WIP high here.
        0x60 | 0xc7 => Some(Duration::from_secs(60)),
        _ => None,
    }
}
